── Attaching packages ─────────────────────────────────────── tidyverse 1.2.1 ──
✔ ggplot2 3.1.0     ✔ purrr   0.2.5
✔ tibble  2.0.1     ✔ dplyr   0.7.8
✔ tidyr   0.8.2     ✔ stringr 1.3.1
✔ readr   1.3.1     ✔ forcats 0.3.0
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
docker: Error response from daemon: driver failed programming external connectivity on endpoint keen_ellis (2868ca61a25b45b43f464d1a0be6c563b9d4fcc46cbe2a94c2dbb53bb252ad21): Bind for 0.0.0.0:4443 failed: port is already allocated.
time="2019-01-31T03:00:04-06:00" level=error msg="error waiting for container: context canceled"
Found 274 new shoes
Found 6 new shoes
Found 31 new shoes
Found 208 new shoes
Found 6 new shoes
Found 31 new shoes
Found 108 new shoes
Found 6 new shoes
Found 27 new shoes
Found 158 new shoes
Found 5 new shoes
Found 16 new shoes
Found 158 new shoes
Found 5 new shoes
Found 24 new shoes
Found 62 new shoes
Found 4 new shoes
Found 19 new shoes
Found 7 new shoes
Found 2 new shoes
Found 4 new shoes
Found 190 new shoes
Found 1 new shoes
Found 7 new shoes
Error: unexpected SPECIAL in "%>%"
Execution halted
